import '../screens/components/main_drawer.dart';

final List<dynamic> data = <dynamic>[
  Entry(
    'Red Line',
    0,
    <Entry>[
      Entry("69th", 40990),
      Entry("79th", 40240),
      Entry("95th/Dan Ryan", 40450),
      Entry("Addison", 41420),
      Entry("Argyle", 41200),
      Entry("87th", 41430),
      Entry("Belmont", 41320),
      Entry("Berwyn", 40340),
      Entry("Bryn Mawr", 41380),
      Entry("Cermak-Chinatown", 41000),
      Entry("Fullerton", 41220),
      Entry("Grand", 40330),
      Entry("Granville", 40760),
      Entry("Harrison"),
      Entry("Garfield"),
      Entry("Howard"),
      Entry("Jackson"),
      Entry("Jarvis"),
      Entry("Lawrence"),
      Entry("Loyola"),
      Entry("Morse"),
      Entry("Lake"),
      Entry("Monroe"),
      Entry("Morse"),
      Entry("North/Clybourn"),
      Entry("Sheridan"),
      Entry("Sox-35th"),
      Entry("Thorndale"),
      Entry("Roosevelt"),
      Entry("Clark/Division"),
      Entry("87th"),
      Entry("47th"),
      Entry("Chicago"),
      Entry("63rd"),
    ],
  ),
  Entry(
    'Brown Line',
    0,
    <Entry>[
      Entry("Washington/Wabash"),
      Entry("Adams/Wabash"),
      Entry("Addison"),
      Entry("Armitage"),
      Entry("Belmont"),
      Entry("Clark/Lake"),
      Entry("Damen"),
      Entry("Diversey"),
      Entry("Francisco"),
      Entry("Fullerton"),
      Entry("Irving Park"),
      Entry("Kedzie"),
      Entry("Kimball"),
      Entry("LaSalle/Van Buren"),
      Entry("Merchandise Mart"),
      Entry("Montrose"),
      Entry("Paulina"),
      Entry("Quincy/Wells"),
      Entry("Rockwell"),
      Entry("Sedgwick"),
      Entry("Southport"),
      Entry("State/Lake"),
      Entry("Washington/Wells"),
    ],
  ),
  Entry(
    'Orange Line',
    0,
    <Entry>[
      Entry("Washington/Wabash"),
      Entry("35th/Archer"),
      Entry("Adams/Wabash"),
      Entry("Ashland"),
      Entry("Clark/Lake"),
      Entry("Halsted"),
      Entry("Harold Washington Library-State/Van Buren"),
      Entry("Kedzie"),
      Entry("LaSalle/Van Buren"),
      Entry("Midway"),
      Entry("Pulaski"),
      Entry("Quincy/Wells"),
      Entry("Roosevelt"),
      Entry("State/Lake"),
      Entry("Washington/Wells"),
      Entry("Western"),
      Entry("Roosevelt"),
    ],
  ),
  Entry(
    'Purple Line',
    0,
    <Entry>[
      Entry("Wilson"),
      Entry("Washington/Wabash"),
      Entry("Wilson"),
      Entry("Adams/Wabash"),
      Entry("Armitage"),
      Entry("Belmont"),
      Entry("Central"),
      Entry("Clark/Lake"),
      Entry("Davis"),
      Entry("Dempster"),
      Entry("Diversey"),
      Entry("Foster"),
      Entry("Fullerton"),
      Entry("Harold Washington Library-State/Van Buren"),
      Entry("Howard"),
      Entry("LaSalle/Van Buren"),
      Entry("Linden"),
      Entry("Main"),
      Entry("Merchandise Mart"),
      Entry("Noyes"),
      Entry("Quincy/Wells"),
      Entry("Sedgwick"),
      Entry("South Boulevard"),
      Entry("State/Lake"),
      Entry("Washington/Wells"),
      Entry("Wellington"),
      Entry("Howard"),
      Entry("Chicago"),

    ],
  ),
  Entry(
    'Blue Line',
    0,
    <Entry>[
      Entry("Austin"),
      Entry("Belmont"),
      Entry("Cicero"),
      Entry("Clark/Lake"),
      Entry("Clinton"),
      Entry("Cumberland"),
      Entry("Damen"),
      Entry("Division"),
      Entry("Forest Park"),
      Entry("Grand"),
      Entry("Harlem"),
      Entry("Division"),
      Entry( "Illinois Medical District"),
      Entry("Irving Park"),
      Entry("Jackson"),
      Entry("Jefferson Park"),
      Entry("Kedzie-Homan"),
      Entry("LaSalle"),
      Entry("Logan Square"),
      Entry("Montrose"),
      Entry("Monroe"),
      Entry("Oak Park"),
      Entry("Pulaski"),
      Entry("Racine"),
      Entry("O'Hare"),
      Entry("Rosemont"),
      Entry("UIC-Halsted"),
      Entry("Washington"),
      Entry("California"),
      Entry("Chicago"),
      Entry("Western"),
      Entry("Addison")
    ],
  ),
  Entry(
    'Green Line',
    <Entry>[
      Entry("35th-Bronzeville-IIT"),
      Entry("43rd"),
      Entry("51st"),
      Entry("Adams/Wabash"),
      Entry("Ashland/63rd"),
      Entry("Austin"),
      Entry("California"),
      Entry("Central"),
      Entry("Cicero"),
      Entry("Clark/Lake"),
      Entry("Clinton"),
      Entry("Conservatory"),
      Entry("Cottage Grove"),
      Entry("Garfield"),
      Entry("Halsted"),
      Entry("Harlem/Lake"),
      Entry("Indiana"),
      Entry("Kedzie"),
      Entry("King Drive"),
      Entry("Laramie"),
      Entry("Morgan"),
      Entry("Oak Park"),
      Entry("Pulaski"),
      Entry("Ridgeland"),
      Entry("Roosevelt"),
      Entry("State/Lake"),
      Entry("Roosevelt"),
      Entry("47th"),
      Entry("Cermak-McCormick Place"),
      Entry("Washington/Wabash"),
      Entry("Ashland"),
    ],
  ),
  Entry(
    'Pink Line',
    0,
    <Entry>[
      Entry("18th"),
      Entry("54th/Cermak"),
      Entry("Adams/Wabash"),
      Entry("California"),
      Entry("Central Park"),
      Entry("Cicero"),
      Entry("Clark/Lake"),
      Entry("Clinton"),
      Entry("Damen"),
      Entry("Harold Washington Library-State/Van Buren"),
      Entry("Kedzie"),
      Entry("Kostner"),
      Entry("LaSalle/Van Buren"),
      Entry("Morgan"),
      Entry("Polk"),
      Entry("Pulaski"),
      Entry("Quincy/Wells"),
      Entry("State/Lake"),
      Entry("Washington/Wells"),
      Entry("Western"),
      Entry("Washington/Wabash"),
      Entry("Ashland"),
    ],
  ),
  Entry(
    'Yellow Line',
    0,
    <Entry>[
      Entry("Howard"),
      Entry("Oakton-Skokie"),
      Entry("Dempster-Skokie"),
      Entry("Oakton-Skokie"),
    ],
  ),
];